project: 
  type: website
  render:
    - "index.qmd"
    - "!GitHub-Guide.qmd"
    - "!README.md"

website: 
  page-navigation: true
  title: "GitHub Guide" 
  site-url: "https://nmfs-opensci.github.io/GitHub-Guide" 
  repo-url: "https://github.com/nmfs-opensci/GitHub-Guide"
  repo-actions: [edit, source, issue]
  favicon: images/favicon.ico
  
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; CC-1.0"
  
  sidebar:
    background: "#D9E3E4"
    logo: "https://raw.githubusercontent.com/nmfs-opensci/assets/main/logo/nmfs-opensci-logo3.png"
    favicon: images/favicon.ico
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://nmfs-opensci.github.io
        text: "NMFS Open Science"
      - icon: github
        href: https://github.com/nmfs-opensci/GitHub-Guide
        text: "GitHub repo for GitHub Guide"
      - icon: filetype-pdf
        href: https://nmfs-opensci.github.io/GitHub-Guide/index.pdf
        text: "PDF of the Guide"

    style: "docked"
    collapse-level: 1

format:
  html:
    theme:
      light: [cosmo, theme.scss] 
      dark: darkly
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - quarto

  
